TacheLongCours/urls.py
from django.urls import path
from . import views

app_name = 'taches'

urlpatterns = [
    path('',views.get_acceuil, name='get_acceuil'),
    path('add_tache/',views.add_tache, name='add_tache'),
    path('<str:slug>/',views.tache_type, name='tache_type'),
    path('detail/<int:id>/',views.detail, name='detail'),
]

accounts/urls.py
from django.urls import path

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TacheLongCours.urls', namespace='taches')),
    path('accounts/', include('django.contrib.auth.urls')),

]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TacheLongCours/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
# Create your models here.


class Tache(models.Model):
    owner = models.ForeignKey(User, related_name='Tache_oner', on_delete=models.CASCADE)
    titre = models.CharField(max_length=50)
    description = models.TextField(max_length=1000)
    date_creation = models.DateTimeField(auto_now=True)
    date_tache = models.DateTimeField(verbose_name='Date de tâche', blank=True)
    category = models.ForeignKey("Category", on_delete=models.DO_NOTHING)
    type_de_tache = models.ForeignKey("TypeDeTache",verbose_name='Type', on_delete=models.DO_NOTHING, null=True)
    

    def __str__(self):
        return self.titre




class Category(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name


class TypeDeTache(models.Model):
    tp = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, null=True)

    def save(self,*args, **kwargs):
        self.slug = slugify(self.tp)
        super(TypeDeTache,self).save(*args, **kwargs)

    def __str__(self):
        return self.tp

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    prenom = models.CharField(max_length=15)
    email = models.EmailField(max_length=20)
    phone_number = models.CharField(max_length=20)


    def __str__(self):
        return self.user

TacheLongCours/forms.py
from django import forms
from .models import Tache, TypeDeTache


class ApplyTach(forms.ModelForm):
    class Meta:
        model = Tache
        fields = '__all__'
        exclude = ['owner']
        widgets = {
            'date_tache': forms.DateInput(format=('%d-%m-%Y'), attrs={'firstDay': 1, 'pattern=': '\d{4}-\d{2}-\d{2}', 'lang': 'pl', 'format': 'yyyy-mm-dd', 'type': 'date'}),
        }

class AddType(forms.ModelForm):
    class Meta:
        model = TypeDeTache
        fields ='__all__'

TacheLongCours/views.py
from django.shortcuts import redirect, render
from .models import Tache, Category, TypeDeTache
from .forms import ApplyTach
from django.urls import reverse
# Create your views here.



def tache_type(request,slug):
    type1 = TypeDeTache.objects.get(slug=slug)
    all_type = TypeDeTache.objects.all()
    tache_type = Tache.objects.all()
    context={'type1':type1, 'types':all_type, 'tache_type':tache_type}
    return render(request,'ponctuel.html',context)


def get_acceuil(request):
    all_type = TypeDeTache.objects.all()
    all_tache = Tache.objects.all()
    return render(request,'test.html',{'types':all_type,'all_tache':all_tache})



def add_tache(request):
    
    if request.method=='POST':
        form = ApplyTach(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()
            return redirect(reverse('taches:add_tache'))
    else:
        form = ApplyTach()
    
    all_type = TypeDeTache.objects.all()
    return render(request,'add_tache.html',{'form':form , 'types':all_type})


def detail(request,id):
    tache_detail = Tache.objects.get(id=id)
    all_type = TypeDeTache.objects.all()
    return render(request,'detail.html',{'detail':tache_detail, 'types':all_type})

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.urls import reverse


from .models import Profile

# Create your views here.

def signup(request):
    if request.method=="POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            #if username se trouve dans la base de données authenticate
            user = authenticate(username = username,password = password)
            login(request,user)
            return redirect('/accounts/profile')
    else:
        form = SignupForm()
    return render(request,'registration/signup.html',{'form':form})

def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})

def profile_edit(request):
    profile = Profile.objects.get(user=request.user)

    if request.method=='POST':
        userform = UserForm(request.POST, instance=request.user)
        profileform = ProfileForm(request.POST, request.FILES, instance=profile)
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofileform = profileform.save(commit=False)
            myprofileform.user = request.user
            myprofileform.save()
            return redirect(reverse('accounts:profile'))

    else:
        userform = UserForm(instance=request.user)
        profileform = ProfileForm(instance=profile)
    return render(request,'accounts/profil_edit.html',{'userform':userform, 'profileform':profileform})

TacheLongCours/templates/add_tache.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block body %}



<div class="tache_area">
    <div class="container" style='margin-top: 60px;'>
        <div class="row" >
            <div class="col-lg-8 mx-auto">
               
               
                <div class="apply_job_form white-bg" >
                    <div class='border-0'>
                     <h4 class='titrepr'>Ajoutez une tâche</h4>
                    </div>
                    <form method="POST" enctype="multipart/form-data">
                    
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_titre" class='typetext1'>Titre</label>
                            <input type="text" name="titre" maxlength="50" placeholder="Titre" title="" required="" id="id_titre" class="form-control formul">
                        </div>
                        <div class="form-group">
                            <label for="id_description" class='typetext1'>Description</label>
                            <textarea name="description" cols="40" rows="10" maxlength="1000" placeholder="Description" title="" required="" id="id_description" class="form-control formul">
                            </textarea>
                        </div>
                        <div class="form-group">
                            <label for="id_date_tache" class='typetext1'>Date de tâche</label>
                            <input type="date" name="date_tache" firstday="1" pattern="=&quot;\d{4}-\d{2}-\d{2}&quot;" format="yyyy-mm-dd" class="form-control formul" placeholder="Date de tâche" title="" id="id_date_tache" lang="pl">
                        </div>
                        <div class="form-group">
                            <label for="id_Type" class='typetext1'>Type</label>
                            <select name="Type" class="form-control formul" title="" required="" id="id_Type">
                            <option value="" selected="">---------</option>
                            {% for type in types %}
                                <option value="1">{{type}}</option>
                            {% endfor %}
                            </select>
                        </div> 
                        <div class="form-group">
                            <label for="id_category" class='typetext1'>Category</label>
                            <select name="category" class="form-control formul" title="" required="" id="id_category">
                            <option value="" selected="">---------</option>
                            {% for category in categorys %}
                                <option value="1">{{category}}</option>
                            {% endfor %}
                            </select>
                        </div> 

                        {% buttons %}
                        <button class="btn boxed-btn3 w-100 formul2" style='margin-top: 10px;' type="submit">Post Now</button>
                        {% endbuttons %}
                       
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock body %}

TacheLongCours/templates/detail.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block body %}
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{ detail.titre }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<div class='container'>
    <div class="row">
        <div class='col-lg-8 tach box'>
            {{detail.description}}

            <form  method="delete">
                {% csrf_token %}
                <input type="submit" value="Delete" />
            </form>

        </div>
    </div>
</div>

  
{% endblock body %}

TacheLongCours/templates/ponctuel.html
{% extends "base.html" %}
{% load bootstrap5 %}


{% block body %}
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>Tâche {{type1}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<div class='container'>
    <div class="row">
        <div class='col-lg-8 tach box'>
            
                        {% csrf_token %}
                        {% for tache in tache_type %}
                        <a href="{% url 'taches:detail' tache.id %}"><h4>{{ tache.titre }}</h4></a>
                        <div >
                            <div class='petit'>
                                <p> Il faut faire la tâche avant : <i class="fa fa-calendar"></i> {{tache.date_tache|date:'d M Y'}}</p>
                            </div>
                        </div>
                        {% endfor %}
                
                
        </div>
        
        <div class='col-lg-6'>
            
        </div> 
    </div>
</div>
  
{% endblock body %}

TacheLongCours/templates/test.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="calendrier1">
                <h1>Calendrier du mois</h1>
                <script>
                    function setStyle(id,style,value)
                    {
                        id.style[style] = value;
                    }
                    function opacite(el,opacity)
                    {
                        setStyle(el,"filter:","alpha(opacity="+opacity+")");
                        setStyle(el,"-moz-opacity",opacity/100);
                        setStyle(el,"-khtml-opacity",opacity/100);
                        setStyle(el,"opacity",opacity/100);
                    }
                    function calendrier()
                    {
                        var date = new Date();
                        var jour = date.getDate();
                        var moi = date.getMonth();
                        var annee = date.getYear();
                        if(annee<=200)
                        {
                            annee += 1900;
                        }
                        mois = new Array('Janvier', 'F&eacute;vrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Ao&ucirc;t', 'Septembre', 'Octobre', 'Novembre', 'D&eacute;cembre');
                        jours_dans_moi = new Array(31,28,31,30,31,30,31,31,30,31,30,31);
                        if(annee%4 == 0 && annee!=1900)
                        {
                            jours_dans_moi[1]=29;
                        }
                        total = jours_dans_moi[moi];
                        var date_aujourdui = jour+' '+mois[moi]+' '+annee;
                        dep_j = date;
                        dep_j.setDate(1);
                        if(dep_j.getDate()==2)
                        {
                            dep_j=setDate(0);
                        }
                        dep_j = dep_j.getDay();
                        document.write('<table class="cal_calendrier" onload="opacite(document.getElementById(\'cal_body\'),20);"><tbody id="cal_body"><tr><th colspan="7">'+date_aujourdui+'</th></tr>');
                        document.write('<tr class="cal_j_semaines"><th>Dim</th><th>Lun</th><th>Mar</th><th>Mer</th><th>Jeu</th><th>Ven</th><th>Sam</th></tr><tr>');
                        sem = 0;
                        for(i=1;i<=dep_j;i++)
                        {
                            document.write('<td class="cal_jours_av_ap">'+(jours_dans_moi[moi-1]-dep_j+i)+'</td>');
                            sem++;
                        }
                        for(i=1;i<=total;i++)
                        {
                            if(sem==0)
                            {
                                document.write('<tr>');
                            }
                            if(jour==i)
                            {
                                document.write('<td class="cal_aujourdhui">'+i+'</td>');
                            }
                            else
                            {
                                document.write('<td>'+i+'</td>');
                            }
                            sem++;
                            if(sem==7)
                            {
                                document.write('</tr>');
                                sem=0;
                            }
                        }
                        for(i=1;sem!=0;i++)
                        {
                            document.write('<td class="cal_jours_av_ap">'+i+'</td>');
                            sem++;
                            if(sem==7)
                            {
                                document.write('</tr>');
                                sem=0;
                            }
                        }
                        document.write('</tbody></table>');
                        opacite(document.getElementById('cal_body'),70);
                        return true;
                    }
                    calendrier();
                </script>
                
            </div>
        </div>
    </div>
</div>
  
{% endblock body %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href= "{% static 'css/acceuil.css' %}">
    <link rel="stylesheet" href= "{% static 'css/calendrier.css' %}">
    <link rel="stylesheet" href= "{% static 'css/tache.css' %}">
    <title>Mes Tâches</title>
  </head>
  <body id='bg' style="background-image :  url('{% static "image/todo.jpg" %}' );">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
        <div class="container-fluid ">
          <a class="navbar-brand" href="#"><i class="fa fa-archive" aria-hidden="true"> Mes tâches</i></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Acceuil</a>
              </li>
              
                
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Type de tâche
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  
                  {% csrf_token %}
                  {% for type in types %}
                    
                  <li><a class="dropdown-item" href="{% url 'taches:tache_type' type.slug %}">{{type}}</a></li> 
                  {% endfor %}
                </ul>
              </li>
         
            </ul>
            <div class='col-lg-1 '>
                <a href="" class='login'>Login</a>
            </div>
            <div class='col-lg-0'>
                <a class="btn boxed-btn3" href="{% url 'taches:add_tache' %}" role="button"><strong> Ajouter une tâche</strong></a>
            </div>
          </div>
        </div>
      </nav>
  

      {% block body %}
        
      {% endblock body %}

      

    <!-- Optional JavaScript; choose one of the two! -->
    
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>